create table book
(
    id     int8 generated by default as identity,
    author varchar(255) not null,
    title  varchar(255) not null,
    primary key (id)
)
create table reads
(
    id        int8 generated by default as identity,
    rate      int2,
    read_date date not null,
    review    varchar(255),
    book_id   int8 not null,
    user_id   int8 not null,
    primary key (id)
)
create table users
(
    id    int8 generated by default as identity,
    email varchar(255) not null,
    name  varchar(255) not null,
    primary key (id)
)
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book
(
    id     int8 generated by default as identity,
    author varchar(255) not null,
    title  varchar(255) not null,
    primary key (id)
)
create table reads
(
    id        int8 generated by default as identity,
    rate      int2,
    read_date date not null,
    review    varchar(255),
    book_id   int8 not null,
    user_id   int8 not null,
    primary key (id)
)
create table users
(
    id    int8 generated by default as identity,
    email varchar(255) not null,
    name  varchar(255) not null,
    primary key (id)
)
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
create table book (id int8 generated by default as identity, author varchar(255) not null, title varchar(255) not null, primary key (id))
create table reads (id int8 generated by default as identity, rate int2, read_date date not null, review varchar(255), book_id int8 not null, user_id int8 not null, primary key (id))
create table users (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id))
alter table if exists book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title)
alter table if exists users add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
alter table if exists reads add constraint BOOK_ID_FK foreign key (book_id) references book
alter table if exists reads add constraint USER_ID_FK foreign key (user_id) references users
