version: "3.5"
services:
  book-server:
    depends_on:
      - db
    container_name: book-server
    build:
      context: ""
      dockerfile: Dockerfile
    image: bookservice:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=example
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    ports:
      - 8041:8041

    networks:
      - spring-network

  db:
    image: postgres
    container_name: db
    build:
      context: docker/postgres-wrapper
      dockerfile: Dockerfile
    volumes:
      - bookservice_data:/data/postgres
      #- ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: rdd2000@ukr.net
      PGADMIN_DEFAULT_PASSWORD: example
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/home/user/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - spring-network
    restart: unless-stopped


networks:
  spring-network:
    driver: bridge

volumes:
  bookservice_data:
  pgadmin:
